import { useMemo, useState, useEffect } from 'react';
import { Boxes, CheckCircle2, Code2, Database, Download, FileJson, GitCompareArrows, Network, Sparkles, History, AlertTriangle, ShieldCheck } from 'lucide-react';
import type { ArchitectureModel } from '@archspace/shared';
import {
  analyzeCodebase,
  applyChange,
  approveArchitecture,
  createProject,
  getScaffold,
  proposeChange,
  saveArchitecture,
  getArchitectureVersions,
  validateProjectArchitecture,
} from '@/services/archspaceApi';
import { useWorkspaceStore } from '@/store/workspaceStore';
import { ArchitectureCanvas } from '@/components/architecture/ArchitectureCanvas';
import { ArchitectureInspector } from '@/components/architecture/ArchitectureInspector';
import { CreateProjectForm } from '@/pages/Project/CreateProjectForm';

export default function App() {
  const { projectId, architecture, selectedNodeId, setProject, setArchitecture, selectNode, updateNode } = useWorkspaceStore();
  const [analysis, setAnalysis] = useState<any>();
  const [change, setChange] = useState<any>();
  const [instruction, setInstruction] = useState('Make payment processing asynchronous.');
  const [scaffold, setScaffold] = useState<any>();
  const [status, setStatus] = useState('Ready');
  const [versions, setVersions] = useState<any[]>([]);
  const [validationResult, setValidationResult] = useState<any>();
  const [activeTab, setActiveTab] = useState<'canvas' | 'validation' | 'versions' | 'scaffold' | 'drift'>('canvas');

  const selectedNode = useMemo(
    () => architecture?.nodes.find((node) => node.id === selectedNodeId),
    [architecture, selectedNodeId],
  );

  useEffect(() => {
    if (projectId) {
      loadHistory();
      runValidation();
    }
  }, [projectId, architecture]);

  async function loadHistory() {
    if (!projectId) return;
    try {
      const historyList = await getArchitectureVersions(projectId);
      setVersions(historyList);
    } catch {
      // Ignore
    }
  }

  async function runValidation() {
    if (!projectId) return;
    try {
      const val = await validateProjectArchitecture(projectId);
      setValidationResult(val);
    } catch {
      // Ignore
    }
  }

  async function handleCreate(input: any) {
    try {
      setStatus('Analyzing requirements with AI...');
      const project = await createProject(input);

      if (project.metadata?.generatedBy === 'ai') {
        setStatus(`✓ Architecture generated by AI (${project.metadata.provider}/${project.metadata.model}).`);
      } else if (project.metadata?.generatedBy === 'heuristic') {
        setStatus('⚠ Architecture generated using heuristic analysis (AI not active).');
      } else {
        setStatus('Architecture generated.');
      }

      setProject(project.id, project.architecture);
      setAnalysis(project.analysis);
      setScaffold(undefined);
      setChange(undefined);
    } catch (error: any) {
      const message = error?.message || 'Unknown error';
      if (error?.code === 'AI_NOT_CONFIGURED') {
        setStatus('✗ AI provider is not configured. Set AI_PROVIDER and AI_API_KEY environment variables.');
      } else {
        setStatus(`✗ ${message}`);
      }
    }
  }

  async function persist(next: ArchitectureModel) {
    setArchitecture(next);
    if (projectId) {
      await saveArchitecture(projectId, next, 'User edited architecture canvas');
      loadHistory();
      runValidation();
    }
  }

  async function handlePropose() {
    if (!projectId) return;
    setStatus('Preparing change preview...');
    setChange(await proposeChange(projectId, instruction));
    setStatus('Change preview ready.');
  }

  async function handleApply() {
    if (!projectId) return;
    const next = await applyChange(projectId, instruction);
    setArchitecture(next);
    setChange(undefined);
    setStatus('Architecture updated.');
    loadHistory();
    runValidation();
  }

  async function handleGenerate() {
    if (!projectId) return;
    setStatus('Generating scaffold from approved architecture...');
    const result = await getScaffold(projectId);
    setScaffold(result);
    setStatus('Scaffold generated.');
  }

  async function handleValidateDemo() {
    if (!projectId) return;
    setStatus('Analyzing codebase & detecting drift...');
    const result = await analyzeCodebase(projectId, [
      {
        path: 'backend/src/controllers/orderController.ts',
        content: "import { pool } from '../database/postgres';\nimport express from 'express';\nrouter.post('/api/orders/internal', async () => pool.query('select 1'));",
      },
      {
        path: 'backend/src/services/paymentService.ts',
        content: "import Stripe from 'stripe';\nexport const stripe = new Stripe(process.env.STRIPE_KEY ?? '');",
      },
      {
        path: 'backend/src/database/mongo.ts',
        content: "import mongoose from 'mongoose';\nexport const connectMongo = () => mongoose.connect('mongodb://localhost:27017/shop');",
      },
    ]);
    setScaffold((current: any) => ({ ...(current ?? {}), validation: result }));
    setStatus('Codebase analysis & drift detection complete.');
  }

  return (
    <div className="shell">
      <aside className="sidebar">
        <div className="brand"><Network size={20} /> ArchSpace AI</div>
        <button className={activeTab === 'canvas' ? 'nav-button active' : 'nav-button'} onClick={() => setActiveTab('canvas')}><Network size={16} /> Canvas</button>
        <button className={activeTab === 'validation' ? 'nav-button active' : 'nav-button'} onClick={() => setActiveTab('validation')}><ShieldCheck size={16} /> Validation</button>
        <button className={activeTab === 'versions' ? 'nav-button active' : 'nav-button'} onClick={() => setActiveTab('versions')}><History size={16} /> History</button>
        <button className={activeTab === 'scaffold' ? 'nav-button active' : 'nav-button'} onClick={() => setActiveTab('scaffold')}><Code2 size={16} /> Scaffold</button>
        <button className={activeTab === 'drift' ? 'nav-button active' : 'nav-button'} onClick={() => setActiveTab('drift')}><GitCompareArrows size={16} /> Drift Report</button>
      </aside>

      <main className="workspace">
        <header className="topbar">
          <div>
            <h1>{architecture?.projectName ?? 'AI Architecture-to-Code Workspace'}</h1>
            <p>{status}</p>
          </div>
          <div className="actions">
            <button disabled={!projectId} onClick={async () => { if (projectId) { setArchitecture(await approveArchitecture(projectId)); runValidation(); } }}><CheckCircle2 size={16} /> Approve</button>
            <button disabled={!projectId} onClick={handleGenerate}><Code2 size={16} /> Generate Scaffold</button>
            <a className={!projectId ? 'disabled link-button' : 'link-button'} href={projectId ? `/api/projects/${projectId}/export/project.zip` : undefined}><Download size={16} /> ZIP</a>
            <a className={!projectId ? 'disabled link-button' : 'link-button'} href={projectId ? `/api/projects/${projectId}/export/architecture.json` : undefined}><FileJson size={16} /> JSON</a>
          </div>
        </header>

        {!architecture ? (
          <section className="start panel">
            <CreateProjectForm onCreate={handleCreate} />
          </section>
        ) : (
          <>
            {activeTab === 'canvas' && (
              <section className="main-grid">
                <div className="canvas-wrap">
                  <ArchitectureCanvas architecture={architecture} onChange={persist} onSelect={selectNode} />
                </div>
                <ArchitectureInspector node={selectedNode} onUpdate={(patch) => selectedNode && updateNode(selectedNode.id, patch)} />
              </section>
            )}

            {activeTab === 'validation' && (
              <section className="panel-tab">
                <h2><ShieldCheck size={18} /> Canonical Architecture Validation Rules</h2>
                {validationResult ? (
                  <div>
                    <p className="summary-bar">
                      Status: {validationResult.valid ? '✓ VALID ARCHITECTURE' : '✗ ARCHITECTURE HAS ERRORS'} |
                      Errors: {validationResult.errorCount} | Warnings: {validationResult.warningCount}
                    </p>
                    <ul className="finding-list">
                      {validationResult.findings.map((f: any, idx: number) => (
                        <li key={idx} className={`finding ${f.severity.toLowerCase()}`}>
                          <strong>[{f.severity}] {f.rule}</strong> ({f.component}): {f.message}
                          <p className="recommendation"><em>Recommendation:</em> {f.recommendation}</p>
                        </li>
                      ))}
                    </ul>
                  </div>
                ) : <button onClick={runValidation}>Run Architecture Validation</button>}
              </section>
            )}

            {activeTab === 'versions' && (
              <section className="panel-tab">
                <h2><History size={18} /> Architecture Version History</h2>
                <ul className="version-timeline">
                  {versions.map((v) => (
                    <li key={v.version} className="version-item">
                      <div className="version-badge">Version {v.version}</div>
                      <div className="version-details">
                        <strong>Source: {v.source}</strong> — <span>{v.changeDescription}</span>
                        <small>Saved: {new Date(v.createdAt).toLocaleString()}</small>
                      </div>
                    </li>
                  ))}
                </ul>
              </section>
            )}

            {activeTab === 'scaffold' && (
              <section className="panel-tab">
                <h2><Code2 size={18} /> Architecture-Aware Generated Project Scaffold</h2>
                <button disabled={!projectId} onClick={handleGenerate}>Refresh Scaffold</button>
                {scaffold?.tree ? (
                  <div className="tree-preview">
                    <h3>Generated Files ({scaffold.tree.length})</h3>
                    <ul>{scaffold.tree.map((path: string) => <li key={path}>{path}</li>)}</ul>
                  </div>
                ) : <p>Click 'Generate Scaffold' to build architecture-aware files with implementation guidance comments.</p>}
              </section>
            )}

            {activeTab === 'drift' && (
              <section className="panel-tab">
                <h2><GitCompareArrows size={18} /> Codebase Analyzer & Architecture Drift Report</h2>
                <button disabled={!projectId} onClick={handleValidateDemo}>Run Codebase Scan & Drift Compare</button>
                {scaffold?.validation?.driftReport ? (
                  <div className="drift-report">
                    <h3>Intended vs Actual Architecture Mismatch</h3>
                    <p>Critical: {scaffold.validation.driftReport.criticalCount} | High: {scaffold.validation.driftReport.highCount} | Medium: {scaffold.validation.driftReport.mediumCount}</p>
                    <ul>
                      {scaffold.validation.driftReport.findings.map((finding: any, idx: number) => (
                        <li key={idx} className="finding high">
                          <strong>[{finding.severity}] {finding.category.toUpperCase()} DRIFT</strong> ({finding.affectedComponent})
                          <p>Expected: <code>{finding.expected}</code> | Actual: <code>{finding.actual}</code></p>
                          <p>{finding.explanation}</p>
                          <p><em>Fix:</em> {finding.recommendation}</p>
                        </li>
                      ))}
                    </ul>
                  </div>
                ) : <p>Click 'Run Codebase Scan & Drift Compare' to analyze project files against approved architecture specification.</p>}
              </section>
            )}
          </>
        )}

        <section className="bottom">
          <div className="panel assistant">
            <h2><Sparkles size={16} /> Architecture Change</h2>
            <div className="inline">
              <input value={instruction} onChange={(event) => setInstruction(event.target.value)} />
              <button disabled={!projectId} onClick={handlePropose}>Preview</button>
              <button disabled={!change} onClick={handleApply}>Apply</button>
            </div>
            {change && (
              <div className="preview">
                <strong>{change.summary}</strong>
                <p>Added: {change.additions.join(', ') || 'None'}</p>
                <p>Modified: {change.modifications.join(', ') || 'None'}</p>
                <p>Impact: {change.impact.join('; ')}</p>
              </div>
            )}
          </div>

          <div className="panel">
            <h2><Boxes size={16} /> Requirements</h2>
            {analysis ? <ul>{analysis.functional.map((item: string) => <li key={item}>{item}</li>)}</ul> : <p>Create a project to see structured requirements.</p>}
          </div>

          <div className="panel">
            <h2><AlertTriangle size={16} /> Quick Validation</h2>
            {validationResult ? (
              <p>{validationResult.valid ? '✓ Valid Architecture' : `⚠ ${validationResult.errorCount} Error(s), ${validationResult.warningCount} Warning(s)`}</p>
            ) : <p>No validation run yet.</p>}
          </div>
        </section>
      </main>
    </div>
  );
}
